#!/usr/bin/env bash
set -euo pipefail

ENV_VARS=(
  AI_CONTAINER_CODEX_API_KEY
  AI_CONTAINER_GEMINI_API_KEY
  AI_CONTAINER_GOOGLE_GEMINI_BASE_URL
  AI_CONTAINER_ANTHROPIC_API_KEY
  AI_CONTAINER_ANTHROPIC_BASE_URL
  AI_CONTAINER_UNATTENDED
  AI_CONTAINER_CLAUDE_UNATTENDED_FLAGS
  AI_CONTAINER_CODEX_UNATTENDED_FLAGS
  AI_CONTAINER_GEMINI_UNATTENDED_FLAGS
  AI_CONTAINER_BOOTSTRAP_PROFILE
  AI_CONTAINER_BOOTSTRAP_PROMPT_FILE
  AI_CONTAINER_BOOTSTRAP_PROMPT
)

DEFAULT_ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/ai-container/env"
ENV_FILE="$DEFAULT_ENV_FILE"
SHELL_NAME=""
RC_FILE=""

usage() {
  cat <<EOF
Usage: scripts/init-host-env.sh [--shell zsh|bash] [--env-file PATH] [--rc-file PATH]

Creates/updates a persistent host env file (default: $DEFAULT_ENV_FILE) and sources it from your shell rc.

Re-run anytime to overwrite/update values.
Type CLEAR to remove a value.
EOF
}

detect_shell() {
  if [ -n "${SHELL_NAME}" ]; then
    return 0
  fi
  case "${SHELL:-}" in
    */zsh) SHELL_NAME="zsh" ;;
    */bash) SHELL_NAME="bash" ;;
    *) SHELL_NAME="zsh" ;;
  esac
}

default_rc_file() {
  if [ -n "${RC_FILE}" ]; then
    return 0
  fi
  detect_shell
  case "$SHELL_NAME" in
    zsh) RC_FILE="$HOME/.zshrc" ;;
    bash) RC_FILE="$HOME/.bashrc" ;;
    *) RC_FILE="$HOME/.zshrc" ;;
  esac
}

quote_sh() {
  local s="$1"
  s="${s//\'/\'\\\'\'}"
  printf "'%s'" "$s"
}

is_var_present_in_env_file() {
  local var_name="$1"
  [ -f "$ENV_FILE" ] && grep -E "^[[:space:]]*export[[:space:]]+$var_name=" "$ENV_FILE" >/dev/null 2>&1
}

write_env_file() {
  local tmp_file
  tmp_file="$(mktemp)"

  umask 077
  mkdir -p "$(dirname "$ENV_FILE")"

  {
    printf '%s\n' "# Generated by ai-container: scripts/init-host-env.sh"
    printf '%s\n' "# Do not commit this file. It contains secrets."
    printf '\n'
    for var_name in "${ENV_VARS[@]}"; do
      local val="${VALUES[$var_name]-}"
      if [ -n "$val" ]; then
        printf 'export %s=%s\n' "$var_name" "$(quote_sh "$val")"
      fi
    done
  } >"$tmp_file"

  mv "$tmp_file" "$ENV_FILE"
  chmod 600 "$ENV_FILE" || true
}

ensure_rc_sources_env_file() {
  default_rc_file
  mkdir -p "$(dirname "$RC_FILE")" 2>/dev/null || true
  touch "$RC_FILE"

  local source_line
  source_line="source \"$ENV_FILE\""

  if grep -F "$source_line" "$RC_FILE" >/dev/null 2>&1; then
    return 0
  fi

  {
    printf '\n# ai-container\n%s\n' "$source_line"
  } >>"$RC_FILE"
}

declare -A VALUES=()

parse_args() {
  while [ $# -gt 0 ]; do
    case "$1" in
      -h|--help)
        usage
        exit 0
        ;;
      --env-file)
        ENV_FILE="${2:-}"
        shift 2
        ;;
      --rc-file)
        RC_FILE="${2:-}"
        shift 2
        ;;
      --shell)
        SHELL_NAME="${2:-}"
        shift 2
        ;;
      *)
        printf 'Unknown argument: %s\n' "$1" >&2
        usage >&2
        exit 2
        ;;
    esac
  done
}

prompt_values() {
  printf 'Target env file: %s\n' "$ENV_FILE"
  default_rc_file
  printf 'Shell rc file:   %s\n\n' "$RC_FILE"

  for var_name in "${ENV_VARS[@]}"; do
    local hint=""
    if is_var_present_in_env_file "$var_name"; then
      hint=" (currently set)"
    fi

    printf 'Enter %s%s (empty=keep, CLEAR=unset): ' "$var_name" "$hint"
    local input=""
    IFS= read -r input

    if [ "$input" = "CLEAR" ]; then
      VALUES["$var_name"]=""
      continue
    fi

    if [ -z "$input" ]; then
      # Keep existing value if present; otherwise keep empty.
      if [ -f "$ENV_FILE" ]; then
        local existing=""
        existing="$(sed -n -E "s/^[[:space:]]*export[[:space:]]+$var_name=(.*)$/\\1/p" "$ENV_FILE" | tail -n 1 || true)"
        if [ -n "$existing" ]; then
          # If existing is quoted, source it via a subshell to preserve exact value.
          local resolved=""
          resolved="$(bash -lc "set -a; source \"$ENV_FILE\" >/dev/null 2>&1 || true; printf '%s' \"\${$var_name-}\"" || true)"
          VALUES["$var_name"]="$resolved"
        fi
      fi
      continue
    fi

    VALUES["$var_name"]="$input"
  done
}

main() {
  parse_args "$@"
  detect_shell
  default_rc_file

  prompt_values
  write_env_file
  ensure_rc_sources_env_file

  printf '\nDone.\n'
  printf 'To apply in current shell, run:\n'
  printf '  source "%s"\n' "$ENV_FILE"
  printf 'Or restart your terminal.\n'
}

main "$@"
