#!/usr/bin/env fish

function usage
    echo "Usage: scripts/init-host-env.fish [--env-file PATH]"
    echo
    echo "Creates/updates a persistent Fish env file and installs it into fish conf.d so it's auto-loaded."
    echo "Re-run anytime to overwrite/update values."
    echo "Type CLEAR to remove a value."
end

set -l default_env_file "$XDG_CONFIG_HOME/ai-container/env.fish"
if test -z "$XDG_CONFIG_HOME"
    set default_env_file "$HOME/.config/ai-container/env.fish"
end

set -l env_file "$default_env_file"
set -l confd_dir "$HOME/.config/fish/conf.d"
set -l confd_file "$confd_dir/ai-container.fish"

set -l argv_copy $argv
while test (count $argv_copy) -gt 0
    switch $argv_copy[1]
        case -h --help
            usage
            exit 0
        case --env-file
            if test (count $argv_copy) -lt 2
                echo "Missing value for --env-file" >&2
                exit 2
            end
            set env_file $argv_copy[2]
            set argv_copy $argv_copy[3..-1]
            continue
        case '*'
            echo "Unknown argument: $argv_copy[1]" >&2
            usage >&2
            exit 2
    end
end

set -l vars \
    AI_CONTAINER_CODEX_API_KEY \
    AI_CONTAINER_GEMINI_API_KEY \
    AI_CONTAINER_GOOGLE_GEMINI_BASE_URL \
    AI_CONTAINER_ANTHROPIC_API_KEY \
    AI_CONTAINER_ANTHROPIC_BASE_URL \
    AI_CONTAINER_UNATTENDED \
    AI_CONTAINER_CLAUDE_UNATTENDED_FLAGS \
    AI_CONTAINER_CODEX_UNATTENDED_FLAGS \
    AI_CONTAINER_GEMINI_UNATTENDED_FLAGS

mkdir -p (dirname "$env_file")
mkdir -p "$confd_dir"

if test -f "$env_file"
    source "$env_file" >/dev/null 2>&1
end

echo "Target env file: $env_file"
echo "Fish conf.d:     $confd_file"
echo

set -l lines
set lines $lines "# Generated by ai-container: scripts/init-host-env.fish"
set lines $lines "# Do not commit this file. It contains secrets."
set lines $lines ""

for var_name in $vars
    set -l hint ""
    if set -q $var_name
        set hint " (currently set)"
    end

    read -P "Enter $var_name$hint (empty=keep, CLEAR=unset): " input

    if test "$input" = "CLEAR"
        continue
    end

    if test -z "$input"
        if set -q $var_name
            set input (eval echo \\$$var_name)
        else
            continue
        end
    end

    set -l escaped (string replace -a "'" "\\'" -- "$input")
    set lines $lines "set -gx $var_name '$escaped'"
end

printf "%s\n" $lines >"$env_file"
chmod 600 "$env_file" >/dev/null 2>&1

printf "%s\n" "source \"$env_file\"" >"$confd_file"

echo
echo "Done."
echo "To apply in current shell, run:"
echo "  source \"$env_file\""
echo "Or restart your terminal."

